
// This file has been generated by the GUI designer. Do not modify.
namespace simpel_algo
{
	public partial class fibonanci
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label label2;

		private global::Gtk.Entry entry1;

		private global::Gtk.Button button2;

		private global::Gtk.Entry entry3;

		private global::Gtk.Entry entry2;

		private global::Gtk.Label label1;

		private global::Gtk.Label label3;

		private global::Gtk.Label label5;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget simpel_algo.fibonanci
			this.Name = "simpel_algo.fibonanci";
			this.Title = global::Mono.Unix.Catalog.GetString("fibonanci");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child simpel_algo.fibonanci.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Angka pertama");
			this.fixed1.Add(this.label2);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
			w1.X = 43;
			w1.Y = 38;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry1 = new global::Gtk.Entry();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '•';
			this.fixed1.Add(this.entry1);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry1]));
			w2.X = 184;
			w2.Y = 30;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button2 = new global::Gtk.Button();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString("Proses");
			this.fixed1.Add(this.button2);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button2]));
			w3.X = 135;
			w3.Y = 126;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry3 = new global::Gtk.Entry();
			this.entry3.CanFocus = true;
			this.entry3.Name = "entry3";
			this.entry3.IsEditable = true;
			this.entry3.InvisibleChar = '•';
			this.fixed1.Add(this.entry3);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry3]));
			w4.X = 184;
			w4.Y = 94;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry2 = new global::Gtk.Entry();
			this.entry2.CanFocus = true;
			this.entry2.Name = "entry2";
			this.entry2.IsEditable = true;
			this.entry2.InvisibleChar = '•';
			this.fixed1.Add(this.entry2);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry2]));
			w5.X = 183;
			w5.Y = 60;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Angka kedua");
			this.fixed1.Add(this.label1);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
			w6.X = 50;
			w6.Y = 60;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Batas perulangan");
			this.fixed1.Add(this.label3);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
			w7.X = 45;
			w7.Y = 92;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("0");
			this.fixed1.Add(this.label5);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label5]));
			w8.X = 76;
			w8.Y = 168;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.button2.Clicked += new global::System.EventHandler(this.click);
		}
	}
}
